apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-da.fullname" . }}
  labels:
    {{- include "ai-da.labels" . | nindent 4 }}
type: Opaque
data:
  anthropic-api-key: {{ .Values.app.settings.anthropicApiKey | b64enc | quote }}
